// Generated by scripts/generate-blur-data.mjs — do not edit by hand.
// Tiny previews shown by next/image while the real photo loads.

export const imageBlurData: Record<string, string> = {
  "ayder-plateau":
    "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoMAAgAAwBSJagCdAEQFVdytQAA/f0+RFcvNGkn3CFU4gKukCL3rHKgqpbGpvJ+uBneAAAA",
  "balat-colorful":
    "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoJAAwAAwBSJbACdAEfhn+zCWEAAP6ZQFZz3GEqqwXI2u6uSf9/ip9x+eYyanREbUWbeExFkaLPB5SB02n762vporacJV8p+VX2byAh4KAAAA==",
  "balat-houses":
    "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoMAAkAAwBSJQBOkCYidinQCAwA4mfsslOzvbvy1dET5C7B+Q/r50NKSnX4fz/dNQkbpd98XTaBfWmoOEe2qEeNYlHhVvgA",
  "balat-street":
    "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoJAAwAAwBSJagCdAELVY5QlAKAAP7YQxsaZdDJg0UPJ8CTxCZOUtlNkYlGA/0t1bYPtsfae8nnWN/+Lite5xRxvahfTdnkriWkSxAA",
  "bali-rice-fields":
    "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoMAAgAAwBSJaACdADbUj4AAP7Q+qaHGTaARJRwCj/01K2r6NQUB1Q5ci3mhfk261BiZeAA",
  "bali-terraces-path":
    "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoMAAgAAwBSJZgCdADz5bDqOAD+Gfv8yoahZqqkMb3G+gcWRcG85yiIoKEH5VMLnD9UoxbDfIZPeMEAAAA=",
  "bali-terraces":
    "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoMAAgAAwBSJagCdACQQbgAAP5J9TnYhVY4Wn8Q8DNtz7THSYExQXxO6EZbOaEJxuge0FAA",
  "cappadocia-aerial":
    "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoMAAgAAwBSJQBOgB6VvLglbgAA/pGlgpkXM1tVVNj+EJUyGq3LCVFDK4/Vm94S8KV6AF7QdwETcAAA",
  "cappadocia-balloon-close":
    "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoJAAwAAwBSJQBOgCFsPH/+atAA/usnXJkGp9wkdHL3cIx66n3UWSBMb00/NiXSy9DtyYO8w8nRlInN3nFFWa3YAAA=",
  "cappadocia-balloons":
    "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAQCdASoMAAgAAwBSJZACdADZkRXgAP73LFQn1Gn5fVY+W5/EXaYw/+USdljlKkESE+2KM8s0RBQPktiovbcYZbOIAAAA",
  "firtina-creek":
    "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAQCdASoJAAwAAwBSJYgC7AEO9EDCE+AA/pqfnm5TbxFrGC7WQRXZpTX8YoWlYXWP0XJh8AA=",
  "kas-harbour":
    "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQAgCdASoMAAcAAwBSJQBOgCPgbCAFAroAAP7c5VE31OBnys6Ct83yufWioMNK+eFAWN3457iHwRKcHFrV6jYCVo3qAAAA",
  "kas-limanagzi":
    "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQAgCdASoMAAkAAwBSJQBOiP/wPRNEaX8cAP6RvgaEDIxMeclhz23mLBi+3umEAL0qdU9MKEOw9VQEKRsCNn8uqUT5uOP8AAA=",
  "kas-sunset":
    "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAABQAgCdASoMAAcAAwBSJZQCdH8GJ/geqA+r2gAA/rdwsZ/YLMgTl5Z/VrJDFWbbXZAca5CeNlRqtVavYAA=",
  "oludeniz-lagoon":
    "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoMAAUAAwBSJZgCdAD1TbdmwAD+lNbL8IT70HE8KGzxEb9rK730iK4kj9MTYc1TNLk7Ca5ESFFCQAAA",
  "oludeniz-paragliding":
    "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoMAAgAAwBSJYgCdAEQEnqIhwAA/fx2gSXD+vd60KRCHRZmG43JoyZjPFIoGfcHiZvRjiRmsvEf3iLQ5XQAAA==",
  "oludeniz-swimming":
    "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAAAQAgCdASoMAAgAAwBSJZgCdAD5j5fQrdQAAP7Hct3Y91QVcS52Taetv0EN7h80Ooi03wnHR5hOD98x2izBjacAAAA=",
};
